using Microsoft.EntityFrameworkCore.Migrations;

namespace SalonOS.Infrastructure.Migrations;

/// <summary>
/// Migration to add TenantId to all tenant-owned entities.
/// This is a conceptual migration - actual migration will be generated by EF Core.
/// </summary>
public partial class AddTenantId : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // This migration will be generated by EF Core when we update the models
        // For now, we're documenting the required changes:
        
        // 1. SalonService -> CatalogService (add TenantId)
        // 2. Appointment -> Booking (add TenantId)
        // 3. Artist -> Staff (add TenantId)
        // 4. Add global query filters
        // 5. Create indexes on TenantId
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Reverse migration
    }
}
